apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-api
  template:
    metadata:
      labels:
        app: travel-api
    spec:
      containers:
        - name: api
          image: travel-api:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://host.docker.internal:27017/travel-platform
            - name: JWT_SECRET
              value: dev_secret
